import { PeriodMetrics } from '../analytics/metrics';
import { formatCoverageCaptionEn } from '../analytics/coverage';
import { TrendPattern, formatTrendPattern } from '../analytics/trend-patterns';
import { HypoEpisode, formatHypoEpisode } from '../analytics/episodes';
import { DaySplitMetrics } from '../analytics/day-split';
import { Annotation } from '../services/annotations-store.service';

export interface ClinicReportExtras {
  patterns?: TrendPattern[];
  hypos?: HypoEpisode[];
  daySplit?: DaySplitMetrics;
  postMealSummary?: string;
  annotations?: Annotation[];
}

/** Build a printable clinic summary (HTML) for the given period. */
export function buildClinicReportHtml(opts: {
  patientLabel: string;
  periodLabel: string;
  metrics: PeriodMetrics;
  targetLow: number;
  targetHigh: number;
  extras?: ClinicReportExtras;
}): string {
  const { patientLabel, periodLabel, metrics: m, targetLow, targetHigh, extras } = opts;
  const cov = formatCoverageCaptionEn(m.coverage);
  const esc = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const patterns = extras?.patterns?.length
    ? `<h2>Recurring time windows</h2><ul>${extras.patterns
        .map((p) => `<li>${esc(formatTrendPattern(p))}</li>`)
        .join('')}</ul>`
    : '';

  const hypos = extras?.hypos?.length
    ? `<h2>Low episodes</h2><ul>${extras.hypos
        .slice(0, 12)
        .map((e) => `<li>${esc(formatHypoEpisode(e))}</li>`)
        .join('')}</ul>`
    : '';

  const split = extras?.daySplit
    ? `<h2>Weekday vs weekend</h2>
       <table>
         <tr><th>${esc(extras.daySplit.weekdayLabel)} TIR</th><td>${extras.daySplit.weekday.tirPct}% · mean ${esc(extras.daySplit.weekday.meanLabel)} mmol/L</td></tr>
         <tr><th>${esc(extras.daySplit.weekendLabel)} TIR</th><td>${extras.daySplit.weekend.tirPct}% · mean ${esc(extras.daySplit.weekend.meanLabel)} mmol/L</td></tr>
       </table>`
    : '';

  const postMeal = extras?.postMealSummary
    ? `<h2>Post-meal pattern</h2><p>${esc(extras.postMealSummary)}</p>`
    : '';

  const notes = extras?.annotations?.length
    ? `<h2>Carepartner notes</h2><ul>${extras.annotations
        .slice(0, 20)
        .map(
          (a) =>
            `<li>${esc(new Date(a.timestamp).toLocaleString('en-GB'))} · ${esc(a.text)}</li>`
        )
        .join('')}</ul>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>JejkaLink clinic summary</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 640px; margin: 2rem auto; color: #1a1a1a; }
    h1 { font-size: 1.25rem; margin-bottom: 0.25rem; }
    h2 { font-size: 1rem; margin: 1.25rem 0 0.5rem; }
    .meta { color: #666; font-size: 0.9rem; margin-bottom: 1.5rem; }
    table { width: 100%; border-collapse: collapse; }
    th, td { text-align: left; padding: 0.4rem 0; border-bottom: 1px solid #eee; }
    th { font-weight: 600; width: 55%; }
    ul { padding-left: 1.2rem; font-size: 0.9rem; }
    li { margin-bottom: 0.35rem; }
    .foot { margin-top: 1.5rem; font-size: 0.8rem; color: #888; }
  </style>
</head>
<body>
  <h1>Glucose summary</h1>
  <div class="meta">${esc(patientLabel)} · ${esc(periodLabel)} · coverage ${esc(cov)}</div>
  <table>
    <tr><th>Readings in period</th><td>${m.count}</td></tr>
    <tr><th>Mean glucose</th><td>${esc(m.meanLabel)} mmol/L</td></tr>
    <tr><th>GMI</th><td>${esc(m.gmiLabel)}%</td></tr>
    <tr><th>CV</th><td>${esc(m.cvLabel)}%</td></tr>
    <tr><th>Time in range (${targetLow.toFixed(1)}–${targetHigh.toFixed(1)})</th><td>${m.tirPct}%</td></tr>
    <tr><th>Below ${targetLow.toFixed(1)}</th><td>${m.belowPct}%</td></tr>
    <tr><th>Above ${targetHigh.toFixed(1)}</th><td>${m.abovePct}%</td></tr>
    <tr><th>Very low (&lt; 3.0)</th><td>${m.veryLowPct}%</td></tr>
    <tr><th>Very high (&gt; 13.9)</th><td>${m.veryHighPct}%</td></tr>
    <tr><th>Tight range (3.9–7.8)</th><td>${m.tightTirPct}%</td></tr>
    <tr><th>Overnight TIR (22:00–07:00)</th><td>${m.overnightTirPct != null ? m.overnightTirPct + '%' : '—'}</td></tr>
  </table>
  ${patterns}
  ${hypos}
  ${split}
  ${postMeal}
  ${notes}
  <p class="foot">Generated by JejkaLink · backup review only · not for dosing decisions</p>
</body>
</html>`;
}

export function downloadHtmlReport(filename: string, html: string) {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
