import { PeriodMetrics } from '../analytics/metrics';
import { formatCoverageCaptionEn } from '../analytics/coverage';

/** Build a printable clinic summary (HTML) for the given period. */
export function buildClinicReportHtml(opts: {
  patientLabel: string;
  periodLabel: string;
  metrics: PeriodMetrics;
  targetLow: number;
  targetHigh: number;
}): string {
  const { patientLabel, periodLabel, metrics: m, targetLow, targetHigh } = opts;
  const cov = formatCoverageCaptionEn(m.coverage);
  const esc = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>JejkaLink clinic summary</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 640px; margin: 2rem auto; color: #1a1a1a; }
    h1 { font-size: 1.25rem; margin-bottom: 0.25rem; }
    .meta { color: #666; font-size: 0.9rem; margin-bottom: 1.5rem; }
    table { width: 100%; border-collapse: collapse; }
    th, td { text-align: left; padding: 0.4rem 0; border-bottom: 1px solid #eee; }
    th { font-weight: 600; width: 55%; }
    .foot { margin-top: 1.5rem; font-size: 0.8rem; color: #888; }
  </style>
</head>
<body>
  <h1>Glucose summary</h1>
  <div class="meta">${esc(patientLabel)} · ${esc(periodLabel)} · coverage ${esc(cov)}</div>
  <table>
    <tr><th>Readings in period</th><td>${m.count}</td></tr>
    <tr><th>Mean glucose</th><td>${esc(m.meanLabel)} mmol/L</td></tr>
    <tr><th>GMI</th><td>${esc(m.gmiLabel)}%</td></tr>
    <tr><th>CV</th><td>${esc(m.cvLabel)}%</td></tr>
    <tr><th>Time in range (${targetLow.toFixed(1)}–${targetHigh.toFixed(1)})</th><td>${m.tirPct}%</td></tr>
    <tr><th>Below ${targetLow.toFixed(1)}</th><td>${m.belowPct}%</td></tr>
    <tr><th>Above ${targetHigh.toFixed(1)}</th><td>${m.abovePct}%</td></tr>
    <tr><th>Very low (&lt; 3.0)</th><td>${m.veryLowPct}%</td></tr>
    <tr><th>Very high (&gt; 13.9)</th><td>${m.veryHighPct}%</td></tr>
    <tr><th>Tight range (3.9–7.8)</th><td>${m.tightTirPct}%</td></tr>
    <tr><th>Overnight TIR (22:00–07:00)</th><td>${m.overnightTirPct != null ? m.overnightTirPct + '%' : '—'}</td></tr>
  </table>
  <p class="foot">Generated by JejkaLink · backup review only · not for dosing decisions</p>
</body>
</html>`;
}

export function downloadHtmlReport(filename: string, html: string) {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
